#!/bin/bash
trap "exit" INT
OPTIND=1
quiet=0

while getopts "qu" opt; do
    case "$opt" in
    u)  resetuser=1
        ;;
    esac
done

shift $((OPTIND-1))
[ "$1" = "--" ] && shift

echo "Dumping local coinbridge database to $BRIDGE/db..."
rm -f $BRIDGE/db/coinbridge_local.db
pg_dump -Ucoinbridge -hlocalhost coinbridge -f $BRIDGE/db/coinbridge_local.db

echo "Compressing..."
rm -f $BRIDGE/db/coinbridge_local.db.gz
gzip -f $BRIDGE/db/coinbridge_local.db
echo "Database dump ok."

sudo service postgresql restart

echo "Reset database:"

if [ $resetuser -eq 1 ]; then
    echo "- Drop user coinbridge"
    sudo -u postgres dropuser coinbridge &> /dev/null
    sleep 1

    echo "- Create user coinbridge"
    sudo -u postgres createuser -P -D -R -S coinbridge &> /dev/null
    sleep 1
fi

echo " - Drop and create database coinbridge"
sudo -i -u postgres &> /dev/null <<'POSTGRES'
dropdb coinbridge &> /dev/null
createdb -E SQL_ASCII -T template0 coinbridge &> /dev/null
POSTGRES

echo " - SQLAlchemy create_all"
python $BRIDGE/bridge/db.py

echo "Done"
