#!/bin/bash
confirms=`bitcoind gettransaction ${1} | jq '.["confirmations"]'`
psql -Ucoinbridge -hlocalhost -dcoinbridge -c "UPDATE transactions SET confirmations = $confirms, last_confirmation = now() WHERE txhash = '${1}'"
